1.02 update
evoraglobal/sieraapi-docs pull request #6
Opened 2022-09-29 13:17 UTC by CharlieMacnamara

- Added parameter description for enum AreaCovered 'all' value.
- Added note for consumption records.
- Fixed full-stop inconsistencies within changelog.

2022-09-29 13:48 UTC, mattjmatthias requested changes

2022-09-29 13:48 UTC, mattjmatthias commented on source/includes/_consumption.md
> +SEIRA always specifies consumption amounts in <code>kWh</code> for all energy and <code>m3</code> for water. Once in the system, no conversion is performed on these values because all aggregations ar
SEIRA -> SIERA

2022-09-29 14:13 UTC, CharlieMacnamara commented on source/includes/_consumption.md
> +SEIRA always specifies consumption amounts in <code>kWh</code> for all energy and <code>m3</code> for water. Once in the system, no conversion is performed on these values because all aggregations ar
🤦

2022-09-30 09:27 UTC, mattjmatthias requested changes

2022-09-30 09:27 UTC, mattjmatthias commented on source/includes/_consumption.md
> +SIERA always specifies consumption amounts in <code>kWh</code> for all energy and <code>m3</code> for water. Once in the system, no conversion is performed on these values because all aggregations ar
m<sup>3</sup> for the m3, sorry forgot to add this last time

2022-10-03 09:03 UTC, CharlieMacnamara commented on source/includes/_consumption.md
> +SIERA always specifies consumption amounts in <code>kWh</code> for all energy and <code>m3</code> for water. Once in the system, no conversion is performed on these values because all aggregations ar
No worries. Was my assumption about formatting for the units correct?

2022-10-03 09:27 UTC, CharlieMacnamara commented on source/includes/_consumption.md
> +SIERA always specifies consumption amounts in <code>kWh</code> for all energy and <code>m3</code> for water. Once in the system, no conversion is performed on these values because all aggregations ar
Okay, thanks for comparing.

2022-10-03 10:09 UTC, mattjmatthias approved these changes

2022-10-05 13:19 UTC, merged